apiVersion: apps/v1
kind: Deployment
metadata:
    name: wordpress-deployment
    labels:
        app: wordpress
spec:
    replicas: 1
    strategy:
        type: RollingUpdate
        rollingUpdate:
            maxSurge: 1
            maxUnavailable: 1
    selector:
        matchLabels:
            app: wordpress
    template:
        metadata:
            labels:
                app: wordpress
        spec:
            containers:
            - name: wordpress
              image: wordpress
              env:
                - name: WORDPRESS_DB_NAME
                  value: wordpress
                - name: WORDPRESS_DB_USER
                  value: wordpress
                - name: WORDPRESS_DB_PASSWORD
                  value: wordpress
                - name: WORDPRESS_DB_HOST
                  value: mysql-service-clusterip:3306
              volumeMounts:
                - mountPath: /var/www/html
                  name: data-volume
            volumes:
              - name: data-volume
                hostPath:
                  path: /data
                  type: Directory

