apiVersion: v1
kind: Service
metadata:
    name: wordpress-service-nodeport
spec:
    type: NodePort
    ports:
    - targetPort: 80
      port: 80
      nodePort: 32080
    selector:
        app: wordpress
